services:
  assets:
    build:
      context: .
      target: dev
    command: npm run assets:modern
    volumes:
      - .:/app
      - /app/node_modules

  app:
    build:
      context: .
      target: dev
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      assets:
        condition: service_completed_successfully
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

  web:
    profiles:
      - prod
    build:
      context: .
      target: prod
    ports:
      - "8080:80"
